export const userInfo = [
  {
    name: "میلاد",
    lastName: "خلیلی",
    number: 1,
    id: 1,
    gift: 20,
    situation: true,
    src: "/image/milad.png",
  },
  {
    name: "فردین",
    lastName: "خلیلی",
    number: 2,
    id: 2,
    gift: null,
    situation: true,
    src: "/image/fardin.png",
  },
  {
    name: "میثم",
    lastName: "خلیلی",
    number: 3,
    id: 3,
    gift: 10,
    situation: true,
    src: "/image/meysam.png",
  },
  {
    name: "سعدی",
    lastName: "موسی پور",
    number: 4,
    id: 4,
    gift: 16,
    situation: true,
    src: "/image/sadi.png",
  },

  {
    name: "میرزا",
    lastName: "عباسی",
    number: 5,
    id: 5,
    gift: null,
    situation: true,
    src: "/image/mirza.png",
  },
  {
    name: "الهه",
    lastName: "زمانی",
    number: 6,
    id: 6,
    gift: null,
    situation: true,
    src: "/image/elahe.jpg",
  },
  {
    name: "بهار",
    lastName: "ابراهیمی",
    number: 7,
    id: 7,
    gift: null,
    situation: true,
    src: "/image/bahar.png",
  },
  {
    name: "فاطمه",
    lastName: "خلیلی",
    number: 8,
    id: 8,
    gift: 9,
    situation: true,
    src: "/image/fati.png",
  },
  {
    name: "فاطمه",
    lastName: "خلیلی",
    number: 9,
    id: 9,
    gift: 8,
    situation: true,
    src: "/image/fati.png",
  },
  {
    name: "میثم",
    lastName: "خلیلی",
    number: 10,
    id: 10,
    gift: 3,
    situation: true,
    src: "/image/meysam.png",
  },
  {
    name: "احمد",
    lastName: "خلیلی",
    number: 11,
    id: 11,
    gift: null,
    situation: true,
    src: "/image/nobody.jpg",
  },
  {
    name: "بیسکوییت",
    lastName: "خلیلی",
    number: 12,
    id: 12,
    gift: null,
    situation: true,
    src: "/image/mahdi.jpg",
  },
  {
    name: "زهره",
    lastName: "اشرفی",
    number: 13,
    id: 13,
    gift: null,
    situation: true,
    src: "/image/zohre.png",
  },
  {
    name: "فرامرز",
    lastName: "عباسی",
    number: 14,
    id: 14,
    gift: null,
    situation: true,
    src: "/image/faramrz.jpg",
  },
  {
    name: "اعظم",
    lastName: "اشرفی",
    number: 15,
    id: 15,
    gift: 17,
    situation: true,
    src: "/image/azam.png",
  },
  {
    name: "سعدی",
    lastName: "موسی پور",
    number: 16,
    id: 16,
    gift: 4,
    situation: true,
    src: "/image/sadi.png",
  },
  {
    name: "اعظم",
    lastName: "اشرفی",
    number: 17,
    id: 17,
    gift: 15,
    situation: true,
    src: "/image/azam.png",
  },
  {
    name: "رمزیه",
    lastName: "",
    number: 18,
    id: 18,
    gift: 19,
    situation: true,
    src: "/image/ramzie.png",
  },
  {
    name: "رمزیه",
    lastName: "",
    number: 19,
    id: 19,
    gift: 18,
    situation: true,
    src: "/image/ramzie.png",
  },
  {
    name: "میلاد ",
    lastName: "خلیلی",
    number: 20,
    id: 20,
    gift: 1,
    situation: true,
    src: "/image/milad.png",
  },
];
